version: '3.7'

services:
  web:
    build: .
    command: ng serve --host 0.0.0.0 --poll=1000 --prod
    ports:
      - 4200:4200
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:delegated
    environment:
      NDOE_ENV: ${NODE_ENV:-development}

volumes:
  node_modules: